# config_vertical.py

# ── SCREEN ─────────────────────────
WIDTH, HEIGHT = 600, 800

BG_COLOR = (20, 30, 40)
BAR_COLOR = (100, 255, 100)
FISH_COLOR = (255, 80, 80)
TRACK_COLOR = (30, 45, 60)

# ── TRACK (VERTICAL) ───────────────
TRACK_WIDTH = 80
TRACK_HEIGHT = 520

TRACK_X = WIDTH // 2 - TRACK_WIDTH // 2
TRACK_Y = HEIGHT // 2 - TRACK_HEIGHT // 2

# ── PLAYER BAR ─────────────────────
BAR_WIDTH = TRACK_WIDTH
BAR_HEIGHT = 120

BAR_MIN_Y = TRACK_Y 
BAR_MAX_Y = TRACK_Y + TRACK_HEIGHT - BAR_HEIGHT

# ── FISH ───────────────────────────
FISH_SIZE = 26

# ── PROGRESS BAR (VERTICAL) ─────────
PROGRESS_BAR_WIDTH = 18
PROGRESS_BAR_HEIGHT = TRACK_HEIGHT

PROGRESS_BAR_X = TRACK_X + TRACK_WIDTH + 24
PROGRESS_BAR_Y = TRACK_Y

PROGRESS_BAR_COLOR = (255, 255, 255)

PROGRESS_INIT = 0.25
PROGRESS_FILL_ANIM_SPEED = 0.007
PROGRESS_UP_RATE = 0.002
PROGRESS_DOWN_RATE = 0.002

# ── PHYSICS ─────────────────────────
FPS = 60

BAR_MAX_SPEED = 8.0
BAR_FRICTION = 0.94             # inertia control

BAR_FORCE_INC = 0.03
BAR_FORCE_DEC = 0.03
BAR_FORCE_MAX = 0.9

# pull bar DOWN (vertical equivalent of DRIFT_LEFT)
BAR_DRIFT_DOWN = 0.5

# ── FISH MOVEMENT ───────────────────
FISH_MOVE_MIN_DIST = 40
FISH_MOVE_MAX_DIST = 160
FISH_MIN_SPEED = 0.5
FISH_MAX_SPEED = 3.0

ENCOUNTER_FREEZE_TIME = 2
